Resources:
  IAMManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: writeCloudWatchLogsPolicy-dev-20230827
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:CreateLogGroup
              - logs:PutLogEvents
            Resource: "*"
    Metadata:
      aws:cdk:path: ECSRoleStack/IAMManagedPolicy
  EcsExecPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: ecsExecPolicy-dev-20230827
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ssmmessages:CreateControlChannel
              - ssmmessages:CreateDataChannel
              - ssmmessages:OpenControlChannel
              - ssmmessages:OpenDataChannel
            Resource: "*"
    Metadata:
      aws:cdk:path: ECSRoleStack/EcsExecPolicy
  S3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: s3Policy-dev-20230827
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
              - logs:DescribeLogGroups
            Effect: Allow
            Resource:
              - arn:aws:logs:*:*:*
          - Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Effect: Allow
            Resource:
              - arn:aws:s3:::demo-fluent-bit
              - arn:aws:s3:::demo-fluent-bit/*
          - Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Effect: Allow
            Resource:
              - "*"
    Metadata:
      aws:cdk:path: ECSRoleStack/S3Policy
  myEcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ""
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Description: Allows ECS tasks to call AWS services on your behalf.
      ManagedPolicyArns:
        - Ref: IAMManagedPolicy
        - Ref: EcsExecPolicy
        - Ref: S3Policy
      MaxSessionDuration: 3600
      Path: /
      RoleName: myEcsTaskRole-dev-20230827
    Metadata:
      aws:cdk:path: ECSRoleStack/myEcsTaskRole
  myEcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2008-10-17"
        Statement:
          - Sid: ""
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Description: Allows ECS tasks to call AWS services on your behalf.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - Ref: IAMManagedPolicy
      MaxSessionDuration: 3600
      Path: /
      RoleName: myEcsTaskExecutionRole-dev-20230827
    Metadata:
      aws:cdk:path: ECSRoleStack/myEcsTaskExecutionRole
  myCodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ""
            Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      Description: Provides CodeDeploy service wide access to perform an ECS blue/green deployment on your behalf.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS
      MaxSessionDuration: 3600
      Path: /
      RoleName: myCodeDeployRole-dev-20230827
    Metadata:
      aws:cdk:path: ECSRoleStack/myCodeDeployRole
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/yWMQQqDMBAA39J7soogePcsiH1A2SZbWY27YKJFxL83bU8zzGEqaBoob/iO1vnZBn7CeU/oZpPTg3GBs31Jh4Ij+V4Du8PkMGig6ycUdVsdfb1V8ZxY5TKinmCKxV6VUOf/FJntuknihWD48wPs2EbIewAAAA==
    Metadata:
      aws:cdk:path: ECSRoleStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Outputs:
  ExportsOutputFnGetAttmyEcsTaskExecutionRoleArnF9BCFC9F:
    Value:
      Fn::GetAtt:
        - myEcsTaskExecutionRole
        - Arn
    Export:
      Name: ECSRoleStack:ExportsOutputFnGetAttmyEcsTaskExecutionRoleArnF9BCFC9F
  ExportsOutputFnGetAttmyEcsTaskRoleArnD6A1FF63:
    Value:
      Fn::GetAtt:
        - myEcsTaskRole
        - Arn
    Export:
      Name: ECSRoleStack:ExportsOutputFnGetAttmyEcsTaskRoleArnD6A1FF63
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

